frontend:
    KEYCLOAL: True
    OIDC_CLIENT_SECRETS: ga4gh/server/config/client_secrets.json
    OIDC_OPENID_REALM: http://192.168.99.100:8080/oidc_callback
    OIDC_ID_TOKEN_COOKIE_SECURE: False
    OIDC_REQUIRE_VERIFIED_EMAIL: False
    OIDC_ID_TOKEN_COOKIE_NAME: id_token
    SECRET_KEY: key
    DEBUG: True
    TESTING: False
    DATA_SOURCE: tests/data/registry.db
    OIDC_GOOGLE_APPS_DOMAIN: None
    OVERWRITE_REDIRECT_URI: http://192.168.99.100:8080/oidc_callback
    OIDC_COOKIE_SECURE: False
    OIDC_ID_TOKEN_COOKIE_PATH: /dev/null

server:
    DEBUG: True
    OIDC_CLIENT_SECRETS: ga4gh/server/config/client_secrets.json
    MAX_CONTENT_LENGTH: 2097152
    MAX_RESPONSE_LENGTH: 1048576
    REQUEST_VALIDATION: True
    DEFAULT_PAGE_SIZE: 100
    FILE_HANDLE_CACHE_MAX_SIZE: 50
    LANDING_MESSAGE_HTML: landing_message.html
    DATA_SOURCE: tests/data/registry.db
    INITIAL_PEERS: ga4gh/server/templates/initial_peers.txt
    CACHE_DIRECTORY: /tmp/ga4gh
    LOGGER_NAME: ga4gh.frontend
    PREFERRED_URL_SCHEME: http
    SEND_FILE_MAX_AGE_DEFAULT: 43200
    SIMULATED_BACKEND_RANDOM_SEED: 0
    SIMULATED_BACKEND_NUM_CALLS: 1
    SIMULATED_BACKEND_VARIANT_DENSITY: 0.5
    SIMULATED_BACKEND_NUM_VARIANT_SETS: 1
    SIMULATED_BACKEND_NUM_REFERENCE_SETS: 1
    SIMULATED_BACKEND_NUM_REFERENCES_PER_REFERENCE_SET: 1
    SIMULATED_BACKEND_NUM_ALIGNMENTS_PER_READ_GROUP: 2
    SIMULATED_BACKEND_NUM_READ_GROUPS_PER_READ_GROUP_SET: 2
    SIMULATED_BACKEND_NUM_PHENOTYPE_ASSOCIATIONS: 2
    SIMULATED_BACKEND_NUM_PHENOTYPE_ASSOCIATION_SETS: 2
    SIMULATED_BACKEND_NUM_RNA_QUANTIFICATION_SETS: 2
    SIMULATED_BACKEND_NUM_EXPRESSION_LEVELS_PER_RNA_QUANT_SET: 2
