FROM centos:7.6.1810
MAINTAINER P-O Quirion <pierre-olivier.quirion@calculquebec.ca>
RUN yum -y update && yum -y install epel-release
RUN yum -y install  \
 python36.x86_64 openssl-devel \
 && yum clean all \
 && rm -rf /var/cache/yum
